﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace HrHelper
{
    public partial class MLModel
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"ID", @"ID"),new InputOutputColumnPair(@"Hons_CGPA", @"Hons_CGPA"),new InputOutputColumnPair(@"Masters_CGPA", @"Masters_CGPA"),new InputOutputColumnPair(@"Experience", @"Experience"),new InputOutputColumnPair(@"MCQ_Exam", @"MCQ_Exam"),new InputOutputColumnPair(@"Written_Exam", @"Written_Exam"),new InputOutputColumnPair(@"Viva", @"Viva")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"ID",@"Hons_CGPA",@"Masters_CGPA",@"Experience",@"MCQ_Exam",@"Written_Exam",@"Viva"}))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.Regression.Trainers.LbfgsPoissonRegression(l1Regularization:0.0312717718799019F,l2Regularization:1.54535240197073F,labelColumnName:@"Total_Marks",featureColumnName:@"Features"));

            return pipeline;
        }
    }
}
